// redux actions
const HOME_MOVIES_REQUEST = 'HOME_MOVIES_REQUEST';
const HOME_MOVIES_REQUEST_SUCCESS = 'HOME_MOVIES_REQUEST_SUCCESS';
const HOME_MOVIES_REQUEST_FAILURE = 'HOME_MOVIES_REQUEST_FAILURE';

// home actions types
const HomeActionTypes = {
  HOME_MOVIES_REQUEST,
  HOME_MOVIES_REQUEST_SUCCESS,
  HOME_MOVIES_REQUEST_FAILURE,
};

export default HomeActionTypes;
