// redux actions
const HOME_POPULAR_MOVIES_REQUEST = 'HOME_POPULAR_MOVIES_REQUEST';
const HOME_POPULAR_MOVIES_REQUEST_SUCCESS = 'HOME_POPULAR_MOVIES_REQUEST_SUCCESS';
const HOME_POPULAR_MOVIES_REQUEST_FAILURE = 'HOME_POPULAR_MOVIES_REQUEST_FAILURE';

const HOME_POPULAR_TV_SHOWS_REQUEST = 'HOME_POPULAR_TV_SHOWS_REQUEST';
const HOME_POPULAR_TV_SHOWS_REQUEST_SUCCESS = 'HOME_POPULAR_TV_SHOWS_REQUEST_SUCCESS';
const HOME_POPULAR_TV_SHOWS_REQUEST_FAILURE = 'HOME_POPULAR_TV_SHOWS_REQUEST_FAILURE';

const HOME_TRENDING_TODAY_REQUEST = 'HOME_TRENDING_TODAY_REQUEST';
const HOME_TRENDING_TODAY_REQUEST_SUCCESS = 'HOME_TRENDING_TODAY_REQUEST_SUCCESS';
const HOME_TRENDING_TODAY_REQUEST_FAILURE = 'HOME_TRENDING_TODAY_REQUEST_FAILURE';

// home actions types
const HomeActionTypes = {
  HOME_POPULAR_MOVIES_REQUEST,
  HOME_POPULAR_MOVIES_REQUEST_SUCCESS,
  HOME_POPULAR_MOVIES_REQUEST_FAILURE,

  HOME_POPULAR_TV_SHOWS_REQUEST,
  HOME_POPULAR_TV_SHOWS_REQUEST_SUCCESS,
  HOME_POPULAR_TV_SHOWS_REQUEST_FAILURE,

  HOME_TRENDING_TODAY_REQUEST,
  HOME_TRENDING_TODAY_REQUEST_SUCCESS,
  HOME_TRENDING_TODAY_REQUEST_FAILURE,
};

export default HomeActionTypes;
